### ISSUE TITLE
PertAlt function request

### ISSUE THREAD

**Issue by angus1095** [varelajosericardo/Simulacion#3]
Hi - I've tried your tool and it looks great. One feature that is missing that I think would be very helpful is a "PertAlt" distribution with the parameters Min, Max, Mode, fMin, fMax, Name. This would provide a distribution with a nice Pert shape but truncated at Min and Max to give an exaggerated frequency to those values.

I tried the existing Truncate function but that gave unusual results and is not as intuitive as specifying the truncation values as frequencies.

Cheers

**Comment by varelajosericardo** [comment]
Hi
Thank you for your feedback, glad you find it useful.
I am uploading a new version with the correct calculation for the truncate
function (the expected value was wrong, I assume that is the unusual result
you were seeing).
I will try to add a specific one for Pert as I did with Normal in a future,
what do you mean specifying the values as frequencies (to truncate at a
specific CDF for minimum and maximum? i.e .at 5% and 95%?)

Kind regards
José

**Comment by angus1095** [comment]
Hello Jose

Thanks for your email.

Yes, for the "PertAlt" distribution it would be useful to specify the
cutoff points in the CDF such that some values can occur outside the
specified MIN, MAX values.

Example image below:
[image: image.png]

Regards
Angus

**Comment by varelajosericardo** [comment]
Hi, I liked the idea (i can not see your image). 

I have added a new Simula_TruncatedPercentiles(Distribution Name, Bottom Percentile, Top Percentile, Name) function that does this for any distribution. I have tested with pert and works very nice not only for pert but all others.
I leave a test file in "Samples/TestTrunc.xls"

**Comment by angus1095** [comment]
Hi - the Truncate function works well but it is not what I was trying to do. I wanted to specify CDF values for Min, Max and allow the distribution to give values outside those boundaries. 
The reason for requesting this feature is to address the inherent optimism bias in some Min, Max estimates by giving those estimates a non-zero likelihood of occurring and also some chance of lower and higher values occurring.

**Comment by varelajosericardo** [comment]
Hi.

I now understand what you need.

You do not need to truncate the distribution, you want to build a pert
distribution without having a certain minimum and maximum but the values at
given percentiles (I.e 5% and 95%)

Unfortunately given that pert distribution is a bounded distribution with
an implicit beta distribution inside it, it is not a closed formula and
will need a numerical integration.

Let me elaborate

For a pert distribution, the percentile function is the inverse of the
incomplete beta function with shape a and b and z point.
I-1z(a,b) where I-1 is the inverse of Iz(a,b) (Incomplete beta function), z
=( x-min )/(max-min), a = 6* (mean -min)/(max-min) and b = 6*
(max-mean)/(max-min) being mean =(min + 4 mode +max)/6.

So for getting the actual min and max of the pert distribution, you would
need to solve for two equations I-1z(a,b) = MinP1 and I-1z(a,b) = MaxP2 and
get the actual min and max from those.

There is no closed form to do it and you must numerically integrate/solve
that,

I have done it for the triangular distribution (see Triangular_Alternative
already in the add-i) that is much easier than pert, I can try to figure it
out for PERT but I see it as too specific and not a generally used
Pert parameters definition.

Regards
José

**Comment by angus1095** [comment]
No problem Jose, thanks for the explanation.

We've found the PertAlt distribution to be very useful in other
applications but it may not be worth the effort in this case.

**Comment by varelajosericardo** [comment]
I have uploaded a new version with the Pert Alternative function
implemented!

Thank you for the challenge!

It was Fun, I tried ChatGPT to figure out a way to implement it.
Although its coding skills are awful,  It gave me hints on how to do it
efficiently after a more-than-a-few hilarious chats.

Hope you can help me to test it, let me know

José

**Comment by angus1095** [comment]
Thank you Jose, it sounds like you had an experience.

I downloaded the latest files but couldn't install them because Microsoft
gave me warnings about a Trojan Horse in the executables.
This seems like a more serious warning than I normally get so I can't
install them sorry.

Angus

**Comment by varelajosericardo** [comment]
Hi
Yes, that’s the weakest point of the tool. Unfortunately it uses the wide
known ExcelDna freeware to connect to excel. Given that some malware uses
it for its “non sanctum” purposes sometimes the anti viruses flag it as
malware.

See the issue in ExcelDna group.
https://groups.google.com/g/ExcelDna/c/L31Yx_YELYI

I fully understand your doubts and see why you can’t use it.

I will look for an updated ExcelDna version to see it can be solved but it
has been happening (falses positives) for years.

Kind regards,
Jose

**Comment by varelajosericardo** [comment]
Uploaded a new version without compression, it should avoid triggering false anti virus flags

**Comment by angus1095** [comment]
Thanks Jose I’ll check it outAngusSent from my mobileOn 9 Apr 2023, at 06:24, Jose Ricardo Varela ***@***.***> wrote:﻿
Uploaded a new version without compression, it should avoid triggering false anti virus
